### ISSUE TITLE
Jobs not started immediately after publish

### ISSUE THREAD

**Issue by Ni55aN** [timgit/pg-boss#105]
Despite of teamSize and teamConcurrency the jobs 2 and 3 will not start until the first is completed

```js
    boss.subscribe('a',{ teamSize: 100, teamConcurrency: 100 },  async (job) => {
        console.log('start '+job.id)
        for(let i = 0; i<10;i++) {
            await delay(1000);
            console.log('do'+job.id)
        }
        console.log('done'+job.id);
    });

    await delay(1000);
    boss.publish('a');
    console.log('publish 1')
    await delay(1000);
    boss.publish('a');
    console.log('publish 2')
    await delay(1000);
    boss.publish('a');
    console.log('publish 3')
    await delay(10000);
    boss.publish('a');
    console.log('publish 4')
```

**Comment by timgit** [comment]
Based on your example, this is how it currently works. Subscriptions are currently processed in batches. If you set teamSize to 100, it will pull up to 100 jobs in a batch, then wait until all of them are complete until pulling another batch. This is a limitation on subscribe() at the moment and something I’d like to enhance. In order to bypass this, you can simply call subscribe twice (or more).

**Comment by Ni55aN** [comment]
> In order to bypass this, you can simply call subscribe twice (or more).

Thanks, I hope it will work stably
