### ISSUE TITLE
Is it possible to disable events?

### ISSUE THREAD

**Issue by bradleyayers** [timgit/pg-boss#113]
I don't use events in my application and would find it useful to disable them to improve the performance on the `job` table. Is this possible, or would it be something you'd be open to adding?

**Comment by timgit** [comment]
Are you referring to the completion jobs that get created?

**Comment by bradleyayers** [comment]
Yes

**Comment by timgit** [comment]
I'm open to this idea, but I'd also like to know some of your performance stats that you've noticed.  How many jobs did you have, how frequently do you move jobs from your hot table to your cold, etc. For example, have you already shortened your the default archive interval to get these jobs moved out sooner?

**Comment by bradleyayers** [comment]
Here's the configuration I'm using:

```
archiveCompletedJobsEvery: "0 minutes",
archiveCheckIntervalMinutes: 15,
deleteArchivedJobsEvery: "0 minutes",
deleteCheckInterval: 1000 * 60 * 15,
expireCheckIntervalMinutes: 15,
```

It works well for standard operation, but my database has some columns on some tables that need updating after deploying new code (they're columns that store summary data that's used in the UI, and persisting them gives fast reads). When I need to update these columns, I typically enqueue a job for each row that needs updating, and the workers then churn through the jobs. At the moment my largest table has ~1M rows, but there's a few other tables so worst case I might queue ~2M jobs.

When I do this I usually set `expirein` to 24 hours to give the workers enough time to work through the data. Another optimisation I could make would be to have the jobs represent batches of rows to process, to reduce the total number of jobs.

The workers are each set to `teamSize: 20, teamConcurrency: 1`, and I have two running (separate servers). I'm not using `batchSize` at the moment, though it's something I've earmarked to look into at some point.

I created this issue because it seemed like the completion jobs add unnecessary overhead (for my use-case), but I'm definitely interested to hear what you think.

**Comment by timgit** [comment]
`expireIn` is a per-job setting.  Are you saying each of these records you're updating would take that long to update?  Setting teamSize or batchSize results in the same batched fetch from the internal job table, the only difference being how many times you acknowledge back to the system when you're done, and if you'd like to use something like `.map()` with your handling logic over an array of jobs instead of working with them one at a time.  `teamConcurrency` would enable you to increase throughput a bit, depending on how many simultaneous queries your system can handle.  I'm guessing you've run into this, since fetching 20 from the job table (both teamSize and batchSize do this) will start the countdown timer, then you need to wait for all 20 to finish one at a time. I would say it seems you're not getting any benefit out of increasing teamSize if concurrency has to be this low.

In regards to keeping the job table squeaky clean, any completion jobs (the ones you opened this issue about) will be moved from the job (hot) table to the archive (cold) table during an archive interval.  For example, if you set `archiveCheckIntervalSeconds = 1`, every second those completion jobs would disappear into the archive.  Then, I would say don't be too concerned about the archive table settings, such as `deleteCheckInterval` unless you notice an issue with that table as well (the only issue I could imagine would be write-related, which would be odd).

I feel like I've sort of rambled through all of this, so please let me know if this helps and if I can clarify anything else.
