### ISSUE TITLE
Run only one job at one time; enqueue multiple

### ISSUE THREAD

**Issue by irfanlone** [timgit/pg-boss#121]
Hi,

Is it possible to have multiple jobs enqueued but only one of them can be active at point? My use case is something like this. 

I enqueue a bunch of workers x1, x2 ..xn (same job name) and a finishing worker Y. Y runs only when  x1, x2 ..xn are completed. I do this by looking in the db and verifying all the workers for a given jobname are completed are not. 

But, there is possibility of Y could be running concurrently for two different sets of data that we are processing. This cause problems for us. 

I looked at this issue https://github.com/timgit/pg-boss/issues/10 and the `singletonKey` feature, which we already use at other place but It doesn't solve the problem because it prevents the workers from getting enqueued after one of them is enqueued and we loose the other jobs at that point.

Let me know if that makes and If i can clarify anything better.

PS: we love pgboss too and is being used in production for few of our services.

**Comment by irfanlone** [comment]
I found a way around this using a combination of `singletonKey` and another worker that just does retries.

**Comment by timgit** [comment]
Irfan, first of all, thanks for the positive feedback.  Glad to hear.  I should first acknowledge that building distributed systems is one of more challenging problems to solve these days, and I have lots of the same issues I keep iterating on and improving as well.

In regards to your specific use case, you didn't include enough details for me to offer a specific recommendation, but I will share with you a common pattern I use to handle orchestration of a job that requires several dependent queues.  

As an example, I recently worked on a feature that required running a half dozen queries to accumulate data in order to generate a report. The report may have timed out if I tried to complete too many things in the same job, so broke each query up into another item queue.  I built a table specifically to hold intermediate query results, then added a tracking mechanism along with `onComplete()` subscriptions in order to check if all items had been completed.  Since onComplete() will fire for both success and failure, this will typically allow me to be reasonably confident when I'm done collecting items then be able to move on any finalization work that is required.  There are also other alternatives I've used, such as an independent monitor job that republishes until items are completed using count(*). 

Ultimately, I've found that best solutions to these types of concurrency use cases are making reasonable attempts at re-desiging your workflows to be more compatible with concurrency, assuming you could have multiple workers sharing the load.  If you are able to pull this off, I think you will find you've increased scalability of your system in the process, too.

Let me know more details of your use case when you get a chance.
