### ISSUE TITLE
fetchCompleted returns only recently completed jobs

### ISSUE THREAD

**Issue by smokir** [timgit/pg-boss#128]
I have a scenario just like one in the #99 and I thought that I could deal with it by using `fetchCompleted` but it appears that once I fetched some part of the grouped jobs they never appear in next fetching. For examples, I publish 4 jobs with name `group-1`, run `fetchCompleted`, get 3 completed jobs, then after some time run `fetchCompleted` again and get only last 1 completed job. `fetch` in the meantime don't fetch completed jobs. 

So is it possible to add some flag to `fetchCompleted` so that it could fetch through all completed (and may be even archived) jobs? 
Or may be make it a new function? 
Or may be you can explain in more detail what you mean [here](https://github.com/timgit/pg-boss/issues/99#issuecomment-450610025)? How this separated store should look like if it needs to be used by separated processes and physical instances? How "task" can handle this situation and not keep process hanging while waiting jobs to complete?

**Comment by timgit** [comment]
`fetchCompleted` will fetch "completion jobs" before they are archived, which survive for an hour by default after a job is completed.  This is a decision I made in order to prevent bloating the job table with jobs that may never be picked up.  If the default archival window of 1 hour is not long enough for you to pick these up because your fetch interval exceeds it, you can customize this via a configuration property in the constructor named `archiveCompletedJobsEvery`. 

If this isn't your actual question, you may also be interested in my response on issue #127, because I'm not following your sequence of "publish, then fetchCompleted". I'm assuming between these steps you are using either subscribe or fetch.

**Comment by smokir** [comment]
What I mean is that in situation like this: 
```
describe('my-custom-test', function() {
  this.timeout(30000);

  let boss;

  before(function(finished) {
    helper.start()
      .then(dabauce => {
        boss = dabauce;
        finished();
      });
  });

  after(function(finished) {
    boss.stop()
      .then(() => finished());
  });

  const baseName = 'my-queue';
  const groupName = baseName + '-group-1';
  const subscribeName = baseName + '*';

  async function jobHandler(currentJob) {
    const {id, data: {type, message}} = currentJob;
    console.log('jobHandler', `\n\tid: ${id}`, `\n\ttype: ${type}`, `\n\tmessage: ${message}`);
    switch (type) {
      case 'do':
        return Promise.resolve();
      case 'fetchCompleted':
        const fetchedJobs = await boss.fetchCompleted(groupName, 3);
        fetchedJobs.forEach(({data: {request: {id, data: {type, message}}}}) => {
          console.log('\tfetched', `\n\t\tid: ${id}`, `\n\t\ttype: ${type}`, `\n\t\tmessage: ${message}`);
        });
        return Promise.resolve();
    }
  }

  async function publishJob(name, type, message) {
    const jobId = await boss.publish(name, {type, message});
    console.log('publishJob', `\n\tid: ${jobId}`, `\n\ttype: ${type}`, `\n\tmessage: ${message}`);
    return Promise.resolve();
  }

  it('my-custom-test', (finished) => {
    boss.subscribe(subscribeName, jobHandler)
      .then(() => publishJob(groupName, 'do', 'first'))
      .then(() => publishJob(groupName, 'do', 'second'))
      .then(() => publishJob(baseName, 'fetchCompleted', 'collect'))
      .then(() => publishJob(groupName, 'do', 'third'))
      .then(() => publishJob(baseName, 'fetchCompleted', 'recollect'))
      .then(() => setTimeout(() => finished(), 30000))
  });
});
```
instead of this output 
```
publishJob
	id: 19e44130-d093-11e9-9afb-c9631d36e949
	type: do
	message: first
publishJob
	id: 19e5a0c0-d093-11e9-9afb-c9631d36e949
	type: do
	message: second
publishJob
	id: 19e5eee0-d093-11e9-9afb-c9631d36e949
	type: fetchCompleted
	message: collect
publishJob
	id: 19e615f0-d093-11e9-9afb-c9631d36e949
	type: do
	message: third
publishJob
	id: 19e63d00-d093-11e9-9afb-c9631d36e949
	type: fetchCompleted
	message: recollect
jobHandler
	id: 19e44130-d093-11e9-9afb-c9631d36e949
	type: do
	message: first
jobHandler
	id: 19e5a0c0-d093-11e9-9afb-c9631d36e949
	type: do
	message: second
jobHandler
	id: 19e5eee0-d093-11e9-9afb-c9631d36e949
	type: fetchCompleted
	message: collect
	fetched
		id: 19e44130-d093-11e9-9afb-c9631d36e949
		type: do
		message: first
	fetched
		id: 19e5a0c0-d093-11e9-9afb-c9631d36e949
		type: do
		message: second
jobHandler
	id: 19e615f0-d093-11e9-9afb-c9631d36e949
	type: do
	message: third
jobHandler
	id: 19e63d00-d093-11e9-9afb-c9631d36e949
	type: fetchCompleted
	message: recollect
	fetched
		id: 19e615f0-d093-11e9-9afb-c9631d36e949
		type: do
		message: third
```
I expect that `recollect` will return 3 fetched jobs instead of 1:
```
jobHandler
	id: 19e63d00-d093-11e9-9afb-c9631d36e949
	type: fetchCompleted
	message: recollect
        fetched
		id: 19e44130-d093-11e9-9afb-c9631d36e949
		type: do
		message: first
	fetched
		id: 19e5a0c0-d093-11e9-9afb-c9631d36e949
		type: do
		message: second
	fetched
		id: 19e615f0-d093-11e9-9afb-c9631d36e949
		type: do
		message: third
```
But even with `"archiveCompletedJobsEvery": "1 day"` in your `test/config.json` I can't fetch jobs that were once fetched with `fetchCompleted`.

**Comment by smokir** [comment]
> I'm not following your sequence of "publish, then fetchCompleted"

* create queue
* subscribe with `jobHandler` callback
* publish jobs: `one`, `two`, `three`, `collect`
  * `one`, `two`, `three` - do smth and return some data with `job.done(null, {someData})`
  * `collect` - do smth only when `one`, `two`, `three` are completed and use `someData` from jobs. if some of `one`, `two`, `three` are incomplete then publish `collect` again.

**Comment by timgit** [comment]
`fetchCompleted()` is the non-polling version of [onComplete()](https://github.com/timgit/pg-boss/blob/master/docs/usage.md#oncompletename--options-handler).  This is the same thing that `subscribe()` does, but for when a job completes.  The important concept here is that job only completes once, and once you've fetched/acknowledged this, it cannot be re-fetched.

I do a lot of orchestrations with pg-boss in our product, so I may be able to offer some advice to steer you in the right direction.  Orchestrations between jobs are outside the scope of features in pg-boss, but the primary building blocks like `onComplete()` can be used to build something of a state machine, provided the state in question is stored elsewhere (such as in another postgres table) and not in the queue.  This is kind of a gray area, I will admit, since it's completely possible to store state in a chained sequence of subsequent jobs using the json data payload, but I don't really recommend it since it's easy to lose this state if or when something bad were to happen if you're not careful about potential job failures and retries, for example.

Let me attempt to provide an example, because it's hard to discuss this in theory alone.  I have a report to run, and it requires data from a 3rd party web api that may be offline because it's flaky.  This report will show data for 3 items, so I need to call the web service 3 times. I decide to create a queue named `service-get-results` which has retries configured in such a way that I can be pretty sure it will keep trying to get data from this flaky web service until it's finally successful.  I will then add an `onComplete('service-get-results')` subscription to gather the results from each run.  This is where you need to determine where you're going to store your state.  One technique I use is to just write the results into a record in another table with some correlation/group id that they all share in common. As each `onComplete()` subscription gets a job, it adds a new record and checks the count of all records with the group id.  Once the total records = 3, I know I'm done and then I can either immediately handle any completion logic, or decide to publish another job to do that if I need to release the current completion job (we're holding this job in active state, remember, during the onComplete() async execution). 

The tricky thing with these is mostly that of concurrency.  This method works very well if you leave the default concurrency set to 1 job at a time and use async job handlers to force pg-boss to only allow 1 job to be running in the same process at a time (it will wait for a promise to resolve if returned).  If you decide you want to increase concurrency, the chances of jobs running in parallel increase, and you can no longer rely on a count = 3 event to happen (like the example above), because the database queries you would typically write do not put exclusive locks on reads.  There are a lot of ways to resolve the concurrency issue in this use case that don't require exclusive locking (which I never do, btw).  I could go into them, such as kicking off a repeating job which can monitor your state during the orchestration, but I think I've probably written enough about it for now, well, at least for this response.

Hope some of all this rambling helps out

**Comment by smokir** [comment]
@timgit thank you very much for your answer! 

I've made a new table and started to store statuses of grouped jobs there and decide to stick more to common query approach.

It all works good in concurrency mode even without any additional locks because I my case the job which needs 3 records is singleton and is executed once.

Thank you again for your help!
