### ISSUE TITLE
Promise for Job Completion by ID?

### ISSUE THREAD

**Issue by blaskovicz** [timgit/pg-boss#188]
Hello and thank you for providing an excellent library!

Is there a way to synchronize on the completion of a job based on the ID returned from `boss.publish(...)`?

I would like to publish a job in the main http handler of my library, perform the work in a separate process, and then receive the result (for example a link to the data in S3 or that the job completed successfully) once the completion has occurred.

I know `onComplete()` can be used for a job name, but is there a direct way to subscribe to the specific job having completed?

**Comment by blaskovicz** [comment]
I ended up hacking around this with something like, but I lose a lot of the features like timeout, error handling, etc.
Is there an easier way?

```ts
  // calling code
  requestData.channelId = uuidv4();
  const q = 'job-queue';
  const qResults = `${q}-results-${requestData.channelId}`;
  const responseHandler = new Promise(async (resolve, reject) => {
    // wait for a response on the results channel
    await boss.subscribe(qResults, async function(job) {
      console.log('received response', job);
      await boss.unsubscribe(qResults);
      // TODO: handle failures
      // job: https://github.com/timgit/pg-boss/blob/master/docs/usage.md#oncompletename--options-handler
      const jobData = job.data as any;
      resolve(jobData);
    });
  });
  boss.publish(q, requestData);
```

```ts
// worker code
const q = 'job-queue';
await boss.subscribe(q, async function(job) {
  console.log('received job', job);
  const jobInput = job.data;
  const qResults = `${q}-results-${jobInput.channelId!}`;
  const result = { ... };
  await boss.publish(qResults, result);
});
```

**Comment by timgit** [comment]
In my applications, I treat job queues as a lower-level subsystem and not primarily a "system of record". Whenever I have something important I want to track, I refer to this as a "task", assign a unique id and then publish 1 or more jobs associated with it.  Once all the jobs are finished, I set a status and data on the task and it serves as the entity in question related to your original question.  

One of the primary reasons I made this choice is how jobs may move from the primary job table to the archive, changing the query used to fetch it if needed later.  Another reason is sometimes a job will be completed with a result, which is not stored in the original job, but rather an associated completion job, complete with its own unique id and subscriptions. And yet another reason is to keep as much database traffic away from the queue tables as possible to free up all capacity for the operation of the queue itself.

I mention all this for context, because I know you can always query the job table directly if you want, and I'm not telling you not to.  But if you decide to start integrating directly with the job table, consider how the queue works internally in your use cases.
