### ISSUE TITLE
No retry for failed jobs

### ISSUE THREAD

**Issue by phips28** [timgit/pg-boss#29]
I am using `done(error)` if an error occurs. 
retrylimit = 2
But it seems to ignore the retry settings for a failed job.

Is this on purpose?

**Comment by timgit** [comment]
Yes, this is intentional and also subjective.  I originally designed retries only for the expiration use case and not for explicit failures.  This could be changed, though.   Can I add your name to the supporters column?

**Comment by phips28** [comment]
ok got it.

We are also using SQS for job queing, and they retry both, expired and failed. 
And we have jobs where the initial attempt fails and a second is successfully.
Errors could be: database connection lost, network timeout or API failures to 3rd parties, ...

So I would say also retry the failed once. Would that be ok for you?

ofc, where is this supporter column? 🙂

**Comment by elmigranto** [comment]
So does this mean we should implement retry logic on client-side? Say I have some webhooks to notify, and want to try each notification up to 3 times with 5 seconds interval. How would I go about that, keep stuff in memory and repeat HTTP requests on my end, and either `done()` or `fail()` after 15 seconds and 3 attempts? (Because judging from source, `fail()`ed job won't be picked up again?)

**Comment by timgit** [comment]
Hey there @elmigranto.  Yes, until I implement this enhancement, you will need to handle this using other techniques.  I wouldn't recommend using in-memory state unless you're ok with losing that job. 

One way in which you could build this using the existing api would be to add a subscription via [`onFail()`](https://github.com/timgit/pg-boss/blob/master/docs/usage.md#onfailname--options-handler) and just republish the job after incrementing a retry counter in the payload.  Then, on each subsequent failure, you can check the retry count and decide if you want to re-publish or not.  You can use the [`startIn`](https://github.com/timgit/pg-boss/blob/master/docs/configuration.md#delayed-jobs) publish option for your delay like the following.

```js
{ startIn : '15 seconds' }
```

**Comment by terehov** [comment]
+1
Yep, definitely something we would need :-) Any updates here?

**Comment by timgit** [comment]
This has become more annoying in my own projects lately as my orchestrations have grown, and so has the amount of expire, fail and complete handlers.  This is going to be quite disruptive, no doubt.

Right now, my thoughts on the new api are 
consolidate api to `onComplete()` only, which has `request` and `response` as usual, with added an `result` prop or something like that with `state` (success or failed), then expired could just be a "reason" for the failure.

remove: `onFail()` and `onExpire()` subs

**Comment by grantcarthew** [comment]
Hi @timgit, for your interest have a look at a job queue I made for some ideas. Checkout the wiki and issues also. https://github.com/grantcarthew/node-rethinkdb-job-queue

Kue gets a lot of attention: https://github.com/Automattic/kue

Bull also: https://github.com/OptimalBits/bull

I recently moved to Postgres and will be using pg-boss at some point (not yet).

**Comment by bradleyayers** [comment]
@grantcarthew Kue gave me a great first impression, if pg-boss ended up at that level, but backed by Postgres, that would be amazing!

**Comment by timgit** [comment]
Thanks, guys.  We were using Kue when I wrote pg-boss, actually.  It was my inspiration along with HangFire.  We had support challenges with the Redis windows port (I know, right?) at the time, and then when I read into the docs about how to "tune" Redis to not lose writes if it were to crash, I was convinced it was just an architectural mismatch to rely too much on system that didn't offer a guaranteed writes.  This is why I drop those hints and the redis docs link in the readme. 

Feel free to make any suggestions on desired features.  I've mostly built this for my own selfish consumption and needs, but I do like the idea of proving the "you can't build a queue in a database" crowd wrong. :)

I know I will find a breaking point of this solution at some point, just being a "plain ole relational database" and all, but until I do, I'm going to keep pushing and optimizing it.  My job processing volumes are now in the thousands, and it's holding up quite well as long as I tune my archiving intervals down to keep the job table as lean as possible.

**Comment by elmigranto** [comment]
I think another obvious example may be [Sidekiq](https://github.com/mperham/sidekiq) which seems to be the default thing everyone uses in Ruby world. Might be worth taking a look on things like Public API structure, etc.

**Comment by timgit** [comment]
All these queues are great. Let's have a feaure per line of code contest.  Coveralls says pg-boss has 413 of 413 relevant lines covered (100.0%).  How many lines of code are in your queue? :trollface:

**Comment by elmigranto** [comment]
I have 400 megabytes `node_modules`, does that count?

**Comment by phips28** [comment]
@timgit I know its a little bit offtopic of this issues.

but can you share your "optimized" config

**Comment by timgit** [comment]
@phips28, I currently have my archive interval to 15min.  

As a specific example, our product at some point has to do some tcp port scanning, and that typically can be pretty quick, so I'll pull down 100 jobs in a batch for that via fetch().  

Most of the time, I'm using a web api that abstracts over fetch(), complete() and fail() so I can share the api's connection pool and distribute as many microservices as I want. In the micros, I've built local queues that monitor themselves and delay fetching more batches until the queue size drops below 50% capacity. 

I do all of my sagas in a centralized worker process with state-based subscriptions like onComplete(). Most of the time, when handling an onComplete(), for example, all I need to do is another publish(), so since that's typically super fast, I'm less concerned about the polling interval.  

One really interesting thing that I've learned about node in this process is that I can easily exhaust the event loop, so I'm keen on improving batching as much as possible here in a 3.0 release so I can mess with the subscribe and publish apis. If you guys run into event loop issues with very large arrays (tens of thousands, for example), a really easy temporary solution is do something like lodash's chunk() api to take an array and chop it into smaller chunks, publish them as "batch" jobs, then immediately subscribe and republish the chunk payloads.

**Comment by timgit** [comment]
The whole point of chunking in my above comment is "get your important stuff out of memory and persisted as fast as possible".  I'm trying to optimize for failure recovery as well.

**Comment by timclipsham** [comment]
@timgit great work with pgboss so far. We're looking to use it, but are also running into challenges with retrying failed events. We're currently experimenting with your "re-publishing + our own retry counter in the payload" workaround from July last year, but I wanted to check if you've made any further progress on a proper solution in the lib before we head too far down that path.

**Comment by timgit** [comment]
@timclipsham, thanks!  Wow, would you look at this 1 year old issue.  😁 Unfortunately I haven't been able to prioritize this above other needs yet.  I don't have a branch started for this effort yet, but I'm thinking I will be able to spend time on it this summer.

**Comment by timclipsham** [comment]
@timgit After exhausting a long list of less-than-ideal options, I realised that updating the state of a failed job to `retry` (that was previously set to `failed`) will re-run the job, and also causes the retry counter to increment. This got me thinking...

Do you think it would make sense to add a monitor for failed events (on a specified frequency set in config), which runs an SQL update across all failed jobs that have not yet exceeded their retry limit to the state `retry`? (these would then be picked up by `fetchNextJob`, and re-processed)

Noted that this isn't the ideal solution you have in mind for the next major version, but being pragmatic I'm wondering if it could give us a "good enough" non-breaking-change solution in the interim.

**Comment by timgit** [comment]
@timclipsham, you're more than welcome to fork and experiment.  I'm at the idea stage on this, not implementation, so I'm not exactly sure what the final solution will be.  If you decide to modify the job record, keep the archive monitor process in mind for race conditions.
