### ISSUE TITLE
`archive` event: name vs meaning

### ISSUE THREAD

**Issue by elmigranto** [timgit/pg-boss#33]
First of all, thanks for a nice lib :)

I've been wondering why job deletion is called "archive"? As far as I can tell from sources, it simply `DELETE`s rows, and I think it is a bit of a stretch to call it archiving; from the docs, I was under impression it moves old stuff to a separate table, something like `pgboss.job_archive`.

Same goes for configuration options (like `archiveCompletedJobsEvery`).

**Comment by timgit** [comment]
Yes, 'archive' is a euphemism for job deletion.  You correctly point out that I haven't mentioned this very clearly in the docs.  I am currently working on docs atm for v2 so I will make another attempt at clarifying this behavior. 

Regardless, I do not intend to keep an archive table for long term job storage. An overall goal of pg-boss is to never become a burden on the database it installs itself into, since that database may or may not contain actual important production data.  Not only do I intend to make sure pg-boss "cleans up" after itself to be a good database citizen, it's also handy to keep performance under control as the number of jobs grow and indexes are maintained.

If you have a use case that requires saving completed job payloads, I would strongly encourage you to configure your archive interval such that you can move them elsewhere before they're deleted.

Thanks for your compliments, and I hope this helps address your question.

**Comment by elmigranto** [comment]
I personally don't want archival table and completely understand that it probably isn't your top priority either, given how no one probably wants it on by default due to effect on db size and upkeeping costs increase.

Simply wanted to bring attention to confusing naming. Maybe with 2.0 and breaking changes on the horizon it wouldn't be late to rename stuff so it is more clear.

Thanks for a prompt reply!

**Comment by timgit** [comment]
Alas, it is too late for this change for 2.0.  But like my grandfather always told me, never fear the semver major.

**Comment by timgit** [comment]
Here's a stab at the clarification: https://github.com/timgit/pg-boss/blob/2.0/docs/configuration.md#job-archive-options

**Comment by timgit** [comment]
Released latest docs.  no name change for now, though.  :)
