### ISSUE TITLE
Queue and job state

### ISSUE THREAD

**Issue by dyashkir** [timgit/pg-boss#35]
I have been looking at replacing a queue we use now (Bull based on redis) with boss(want to get rid of Redis for variety of reasons). I have couple questions. I have couple use cases where I need to provide progress of the jobs to the web clients, looking at the current schema this is not possible? Other simple case is that I have a admin panel that shows jobs as they get added and processed. Is there a way to grab info based on job id? Right now seems like only way to query DB directly. Is this the design you would suggest here

Thank a lot

**Comment by timgit** [comment]
For progress reporting, you're correct. I haven't built anything into the api for external state modifications to jobs (for better or for worse).  So far, I've thought that was a good idea since adding it would introduce a new load on the database for setting and then reacting/polling to that change.  This doesn't mean it's a bad idea, but I'm just letting you know that I intentionally have avoided building this so far.  

In our product, so far I've been able to accomplish long-running progress reporting by breaking large jobs into small jobs, then using the (small job completed count) / (total small job count) for progress percentage.  This reduces boss integration points, but with the added cost to the consumer (you) to orchestrate this.

In regards to an admin panel, I've actually been thinking more about this recently, as I'd like to have said admin panel for my own consumption as well.  Here, too, you're absolutely correct.  Feel free to just query the job table to get a snapshot of job state.  

I'd like to know your feedback on these points, and also a little more information about your specific use case if you can share.  For example, if it's CPU bound, I/O bound, how long-running is it, if you've had to extend the default expiration to prevent a time out, just those little details. 😁

**Comment by dyashkir** [comment]
Thank you.

Use case is long running CPU and memory image analysis code written in C++. Node is used for api, managing everything working together and launching binaries to process images. For some images it can take 5-6GB of memory and eat as much CPU as you can throw at it :( so basically each of those is on a dedicated instance. It can take up to few minutes for come cases to run these things.

So progress quite important, since process is really two step in terms of time, and we want to have more then 0% 50% done for updates. Currently C++ executable just writes stuff into std out for node to catch and update job status.

I think the admin panel reading from table directly is fine, it works. Updates of the job progress is a tough one. I need to think about it.

**Comment by timgit** [comment]
For now, the easiest solution seems to be using the job id during publish to build your state in another database table. Yes, this would mean you also build an api to keep it updated, but it would have the added benefit of being able to store any other state attributes such as status messages, other metrics about your operation, etc.
