### ISSUE TITLE
How to partially fail a batch?

### ISSUE THREAD

**Issue by danilofuchs** [timgit/pg-boss#474]
I'm implementing batch support in my application, and I would like to fail only 1 job of the batch, using `Promise.allSettled`:

```typescript

    await this.boss.work<PgBossJobData<T>>(
      queueName,
      {
        includeMetadata: true,
        pollingIntervalSeconds,
        batchSize,
      },
      async (jobs) => {
        const results = await Promise.allSettled(
          jobs.map((job) => this.runJob(job, queueName, jobHandler)),
        );
        
        const errors = results.filter((result) => result.status === "rejected");

        const successes = results.filter((result) => result.status === "fulfilled");
      },
    );
```

I could use `fetch`, `complete`, `fail` myself, but then I loose all the `Worker` functionality and have to manage polling myself

Would be nice if `work` had an API for that, for example:

```typescript
    await this.boss.work<PgBossJobData<T>>(
      queueName,
      {
        includeMetadata: true,
        pollingIntervalSeconds,
        batchSize,
        autoComplete: false,
      },
      async (jobs, { complete, fail }) => {
        const results = await Promise.allSettled(
          jobs.map((job) => this.runJob(job, queueName, jobHandler)),
        );

        const resultsWithJobId = results
          .map((result, index) => ({ result, jobId: jobs[index].id }))

        for (const {result, jobId} of resultsWithJobId) {
          if (result.status === "rejected") {
            await fail(jobId, result.reason)
          } else {
            await complete(jobId)
          }
        }
      },
    );
```

`work` would only poll again if all jobs have been completed or failed

**Comment by timgit** [comment]
The issue with Promise.allSettled and Promise.all is that it has no concurrency control.  v9 and below had support for this via the p-map package and used the `teamConcurrency` option. However this produced too much complexity for all use cases, since some jobs within a batch may take longer than others, reducing the overall throughput over time.

**Comment by danilofuchs** [comment]
> is that it has no concurrency control

What do you mean by concurrency control in the context of `Promise.allSettled`? Not sure I understood the requirement

**Comment by timgit** [comment]
How many promises run in parallel

**Comment by foteiniskiada** [comment]
We've run into a similar issue, since we have a production system that needs to be upgraded to v10, and it seems it is no longer possible to partially fail a batch of jobs; if one fails all the batch gets failed, which is problematic since it degrades performance. Is there a way to handle these cases by allowing success of non-erroneous jobs?

**Comment by klesgidis** [comment]
In addition, we saw in the [source code](https://github.com/timgit/pg-boss/pull/425/commits/5913a6ef424b100d0dd306c78c5ccc5417596f9d) that you either succeed all jobs or none. The greatest danger here is that if one job from the batch fails, all other jobs will also fail. In that case even the successful jobs will be retried, which means that if a job is not idempotent bigger problems will arise.

**Comment by klesgidis** [comment]
@timgit tagging you, because I am not sure if notifications reaches you in a closed issue

**Comment by foteiniskiada** [comment]
@danilofuchs @timgit Just posting here for visibility a PR that would resolve this issue in our case https://github.com/timgit/pg-boss/pull/524

**Comment by sneko** [comment]
Hi all,

I was previously using v9 with `.work()` and since it was managing just one job, the failure was set to the job automatically. Now from what I understand, a `batchSize` can be use, but since there is no return value possible, `pg-boss` will either consider all `completed` or all `failed` depending on it my handler throws an issue.

I guess I could catch error within a jobs loop, and mark manually the job as `failed`... but it sounds in this case `.work()` is not longer something to deal with, and it's better to use `.fetch()` directly. No? (saying that since returning no error to `pg-boss` would make it marking all `completed` after me.

So now, just a dumb question: is it mandatory to use `batchSize > 1` to make sure if more than X jobs are waiting they run as fast as possible? Having a job fetched is not immediately bypassing the `interval` just to try reading another one (but I agree it makes another round-trip)... If so, I don't get why `.work()` is not handling the logic of calling our own handler multiple times (except offering a few people the chance to batch HTTP requests or so).

Thank you,

**Comment by timgit** [comment]
When you opt into batchSize, yes, you're trading the simplicity of "one job at a time" for the complexity that comes with higher throughput performance.  One of the trade-offs is handling the use case of having some jobs in the batch fail and some that succeed.  In order to try and assist with this, pg-boss will try and auto-complete all jobs, but you can also use try/catch around individual jobs and call `fail()`, `complete()`, and now in some cases, even `delete()`.
