### ISSUE TITLE
Can we say this amazing project is somehow similar to...

### ISSUE THREAD

**Issue by frederikhors** [timgit/pg-boss#86]
Can we say this amazing project is somehow similar to this: https://github.com/chanks/que ?

**Comment by timgit** [comment]
Yes, these projects are similar.  :grinning:

**Comment by frederikhors** [comment]
@timgit is there something you can say about this? https://github.com/chanks/que/issues/228#issuecomment-420699547

This is the author of https://github.com/chanks/que talking about your project, but we have not clear ideas about:

- SKIP LOCKED, rather than advisory locks
- whether you uses LISTEN/NOTIFY

Can you enlighten us about it?

**Comment by timgit** [comment]
Yes, fundamentally, both of our projects are queues built on top of postgresql.  I built pg-boss with a hard requirement of 9.5 and up in order to use SKIP LOCKED exclusively.  All SQL used can be found in the [plans.js file](https://github.com/timgit/pg-boss/blob/master/src/plans.js). I don't use LISTEN or NOTIFY. This is entirely polling and/or fetch based. 

You can read about some of the reasoning behind this feature and advisory locks in https://blog.2ndquadrant.com/what-is-select-skip-locked-for-in-postgresql-9-5/

**Comment by frederikhors** [comment]
@chanks, is this answer about SKIP LOCKED enough to understand the differences with your project?

**Comment by chanks** [comment]
Yep, sounds different! Thanks, @timgit.
